export const V2_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',
  FORBIDDEN: 'FORBIDDEN',
  AUTH_INTERNAL_ERROR: 'AUTH_INTERNAL_ERROR',
  TEAM_CONTEXT_REQUIRED: 'TEAM_CONTEXT_REQUIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SLUG_TAKEN: 'SLUG_TAKEN',
  NOT_FOUND: 'NOT_FOUND',
  KEY_REVOKED: 'KEY_REVOKED',
  POLICY_DENIED: 'POLICY_DENIED',
  SAML_NOT_IMPLEMENTED: 'SAML_NOT_IMPLEMENTED',
  SAML_INVALID_RESPONSE: 'SAML_INVALID_RESPONSE',
  SAML_ASSERTION_REPLAYED: 'SAML_ASSERTION_REPLAYED',
  SAML_ASSERTION_EXPIRED: 'SAML_ASSERTION_EXPIRED',
  SAML_SIGNATURE_INVALID: 'SAML_SIGNATURE_INVALID',
  SAML_RELAYSTATE_INVALID: 'SAML_RELAYSTATE_INVALID',
  SAML_PAYLOAD_TOO_LARGE: 'SAML_PAYLOAD_TOO_LARGE',
  SSO_REQUIRED: 'SSO_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type V2ErrorCode = typeof V2_ERROR_CODES[keyof typeof V2_ERROR_CODES];
