services:
  - type: web
    name: mockapi-backend
    env: node
    plan: starter
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_MODE
        value: otp
      - key: EXPOSE_STACK_TRACE
        value: "false"
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: API_KEY_SECRET
        generateValue: true
      - key: OTP_SECRET
        generateValue: true
