import { AIRuleGenerator } from "@/components/AIRuleGenerator";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import { fetchEndpoint, fetchEndpoints, updateEndpoint, type Endpoint } from "@/lib/api";
import { Bot, Sparkles, Wand2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "react-hot-toast";

type MockRule = {
  path: string;
  method: string;
  response: {
    status: number;
    body: unknown;
    headers?: Record<string, string>;
  };
};

function normalizeGeneratedRule(input: any): MockRule {
  if (input?.response?.status && input?.path && input?.method) {
    return input as MockRule;
  }

  let parsedBody: unknown = input?.responseTemplate ?? input?.body ?? { message: "Generated by AI" };
  if (typeof parsedBody === "string") {
    try {
      parsedBody = JSON.parse(parsedBody);
    } catch {
      // keep as string if it is not valid JSON
    }
  }

  return {
    path: input?.path || "/generated",
    method: input?.method || "GET",
    response: {
      status: Number(input?.statusCode ?? input?.status ?? 200),
      body: parsedBody,
      headers: input?.headers,
    },
  };
}

export default function AIStudioPage() {
  const [endpoints, setEndpoints] = useState<Endpoint[]>([]);
  const [selectedEndpointId, setSelectedEndpointId] = useState<string>("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetchEndpoints()
      .then((list) => {
        setEndpoints(list);
        if (list.length > 0) {
          setSelectedEndpointId(list[0].id);
        }
      })
      .catch(() => {
        toast.error("Failed to load endpoints");
      });
  }, []);

  const selectedEndpoint = useMemo(
    () => endpoints.find((ep) => ep.id === selectedEndpointId) || null,
    [endpoints, selectedEndpointId]
  );

  const handleRuleGenerated = async (generatedRule: any) => {
    if (!selectedEndpointId) {
      toast.error("Select an endpoint first");
      return;
    }

    const normalizedRule = normalizeGeneratedRule(generatedRule);

    try {
      setSaving(true);
      const detail = await fetchEndpoint(selectedEndpointId);
      const existingRules = Array.isArray(detail.rules) ? detail.rules : [];
      await updateEndpoint(selectedEndpointId, {
        rules: [...existingRules, normalizedRule],
      });
      toast.success("AI rule added to endpoint");
    } catch {
      toast.error("Failed to save generated rule");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h2 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <Bot className="h-6 w-6 text-primary" />
          AI Rule Studio
        </h2>
        <p className="text-muted-foreground">
          Generate realistic mock rules from prompts and apply them directly to endpoints.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Target Endpoint</CardTitle>
          <CardDescription>Select where generated rules should be saved.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Select value={selectedEndpointId} onValueChange={setSelectedEndpointId}>
            <SelectTrigger>
              <SelectValue placeholder="Select endpoint" />
            </SelectTrigger>
            <SelectContent>
              {endpoints.map((ep) => (
                <SelectItem key={ep.id} value={ep.id}>
                  {ep.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {selectedEndpoint && (
            <div className="flex items-center gap-2 text-xs">
              <Badge variant="outline">Live URL</Badge>
              <code className="font-mono">{selectedEndpoint.url}</code>
            </div>
          )}
        </CardContent>
      </Card>

      {selectedEndpointId ? (
        <AIRuleGenerator endpointId={selectedEndpointId} onRuleGenerated={handleRuleGenerated} />
      ) : (
        <Card className="border-dashed">
          <CardContent className="py-10 text-center text-muted-foreground">
            <Sparkles className="h-6 w-6 mx-auto mb-3 opacity-60" />
            Create an endpoint first, then generate AI rules.
          </CardContent>
        </Card>
      )}

      <div className="flex justify-end">
        <Button variant="outline" disabled={saving}>
          <Wand2 className="h-4 w-4 mr-2" />
          {saving ? "Applying Rule..." : "Ready"}
        </Button>
      </div>
    </div>
  );
}

